// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqkN1bj8NntOBQjqDQKiu4JJO1G1T2oIQ',
    appId: '1:909998035252:web:8b2ff97c3a116951821561',
    messagingSenderId: '909998035252',
    projectId: 'aukraanantkaya',
    authDomain: 'aukraanantkaya.firebaseapp.com',
    storageBucket: 'aukraanantkaya.firebasestorage.app',
    measurementId: 'G-9JWZJ9C6CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTua672ORdXa-01V1v2wBC6sYDDwglRg4',
    appId: '1:909998035252:android:f851f951dc90d4c2821561',
    messagingSenderId: '909998035252',
    projectId: 'aukraanantkaya',
    storageBucket: 'aukraanantkaya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSSSFC6ow517WWHKCDxqoIsVFJVVDQPTU',
    appId: '1:909998035252:ios:fec7bf3953a9c9d0821561',
    messagingSenderId: '909998035252',
    projectId: 'aukraanantkaya',
    storageBucket: 'aukraanantkaya.firebasestorage.app',
    iosBundleId: 'com.example.aukraAnantkayaSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSSSFC6ow517WWHKCDxqoIsVFJVVDQPTU',
    appId: '1:909998035252:ios:fec7bf3953a9c9d0821561',
    messagingSenderId: '909998035252',
    projectId: 'aukraanantkaya',
    storageBucket: 'aukraanantkaya.firebasestorage.app',
    iosBundleId: 'com.example.aukraAnantkayaSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqkN1bj8NntOBQjqDQKiu4JJO1G1T2oIQ',
    appId: '1:909998035252:web:1185393cb08d5a31821561',
    messagingSenderId: '909998035252',
    projectId: 'aukraanantkaya',
    authDomain: 'aukraanantkaya.firebaseapp.com',
    storageBucket: 'aukraanantkaya.firebasestorage.app',
    measurementId: 'G-36Y2PN0CRP',
  );
}
